### ISSUE TITLE
Are contributions welcome?

### ISSUE THREAD

**Issue by collinmesser** [soroushchehresa/unsplash-wallpapers#11]
Is this the same usplash app that is available here https://apps.apple.com/us/app/unsplash-wallpapers/id1284863847?mt=12 ? I use this little app and love it. I'd really like to contribute if contributions are welcome. I have a few ideas for enhancements.

**Comment by soroushchehresa** [comment]
@collinmesser Hi Collin.
Welcome! I added you as a collaborator to this project.
