### ISSUE TITLE
Wallpaper update not working

### ISSUE THREAD

**Issue by ruink33per** [soroushchehresa/unsplash-wallpapers#13]
Hey, I changed from [splashy](https://splashy.art/) to unsplash-wallpapers v1.1.0 but noticed the daily update is not working (Win10 1909). A shorter update interval would also be nice - e.g. hourly.

**Comment by soroushchehresa** [comment]
@ruink33per [v1.2.0](https://github.com/soroushchehresa/unsplash-wallpapers/releases/tag/v1.2.0)
