### ISSUE TITLE
Set as Wallpaper doesn't work on Windows 10

### ISSUE THREAD

**Issue by ottodoesntknow** [soroushchehresa/unsplash-wallpapers#6]
Just started using your app and when trying to set a photo as wallpaper it just keeps loading and doesn't change the wallpaper.

If you need more details on the issue I can provide them.

**Comment by soroushchehresa** [comment]
@oscargb1 Thanks for the report, I'll check this issue and let you know soon.

**Comment by sandronm** [comment]
Same problem here with the latest version of Windows 10 Pro (1909 18363.752)

**Comment by ruink33per** [comment]
Still a problem on Windows 10 Pro (1909 18363.836) with v1.1.0

**Comment by soroushchehresa** [comment]
This issue is related to the [Wallpaper package](https://github.com/sindresorhus/wallpaper).
