### ISSUE TITLE
Feature Request: recognize display size and query unsplash acordingly

### ISSUE THREAD

**Issue by RowanKaag** [soroushchehresa/unsplash-wallpapers#7]
I'm very impressed with this multi-platform tool, wish I found it earlier! There's one thing I'm facing with macOS though and I'm not sure if this is working as intended. Any wallpaper I download don't fill my screen (3440x1440). I am aware that my screen is wider than most other people will have, but my suggestion might suit others too.

In Unsplash, there's an info pane that allows to see the resolution of the photo as such:
![image](https://user-images.githubusercontent.com/6907625/79611968-060f4780-80fc-11ea-8f08-26acede8f523.png)

Would it be possible to accommodate for the screen size, and use these as query parameters when looking for wallpapers in Unsplash? According to the API it should be possible to do so via, for example, ```photo.urls.raw + "&w=1500&dpr=2"``` - https://unsplash.com/documentation

**Comment by soroushchehresa** [comment]
@RowanKaag  Thanks for your suggestion.
I added this feature in [this commit](https://github.com/soroushchehresa/unsplash-wallpapers/commit/b51f9ab3e223a03b8a9718180b83de505afe73aa) and I'll release it soon with the other new features!

**Comment by soroushchehresa** [comment]
@RowanKaag [v1.2.0](https://github.com/soroushchehresa/unsplash-wallpapers/releases/tag/v1.2.0) just released!
