### ISSUE TITLE
Doesn't update all desktops on macOS

### ISSUE THREAD

**Issue by ggrell** [soroushchehresa/unsplash-wallpapers#8]
Switched to 1.1.0 from old official app. The official app handled setting wallpaper of each desktop, but this version only seems to update the main desktop wallpaper.

macOS 10.14.6

**Comment by soroushchehresa** [comment]
@ggrell Thanks for your report.
I'll fix it and let you know soon.

**Comment by soroushchehresa** [comment]
@ggrell This issue is related to the [Wallpaper package](https://github.com/sindresorhus/wallpaper).
