### ISSUE TITLE
If you have your task barr in the top, the unspashh windows has the wrong location

### ISSUE THREAD

**Issue by nathanredblur** [soroushchehresa/unsplash-wallpapers#9]
If you have your task bar in the top, the unspashh windows has the wrong location.

OS: windows 10
1. so, move your task bar to the top.
2. try to click the unspash icon.

what happen: the windows is hidden.
what should happen: the windows detect the icon location and open in the best location.

**Comment by soroushchehresa** [comment]
@nathanredblur Thanks for your report.
I'll fix it and let you know soon.

**Comment by nathanredblur** [comment]
Nice, thanks :)
